### ISSUE TITLE
How to test the last version?

### ISSUE THREAD

**Issue by costales** [ubports/android_device_fairphone_fp2#1]
Hi Marius,

First, thanks a lot for your work and effort porting Ubuntu to new devices, this is so need in UT!

I watched your video about the FairPhone 2 working even with convergence (gorgerous!!):
https://www.youtube.com/watch?v=JwBf75bHgkE&feature=youtu.be
Please, how could I try that?

I found this:
https://github.com/ubports/android_device_fairphone_fp2
But the code is from 10 months ago and the video is from July.

And these intructions doesn't look to give that convergence:
https://devices.ubports.com/#/FP2

Thanks in advance and best regards!

**Comment by NeoTheThird** [comment]
For the record: https://devices.ubports.com/#/FP2
